### ISSUE TITLE
The tracking was not working in main.py

### ISSUE THREAD

**Issue by wandyu** [liuchangji/kalman-filter-in-single-object-tracking#2]
Hello, I am a beginner at python. I tried to track a single object in the video. But, the video was not running and was not showing any tracking. But, plotting the bounding boxes. Please help me.

**Comment by liuchangji** [comment]
cv2.waitkey(0) is waiting for you to press any key to continue.So please to press anykey

**Comment by hasndh** [comment]
I pressed the key. I meant the tracking box is not followed along with the pedestrian. only the first bounding box for the tracking is plotted. How to do that?

**Comment by hasndh** [comment]
Could you please add the license to this?
